export const SITE_CONFIG = {
  name: "Klarden UI",
  description:
    "Klarden UI is a free, open-source collection of premium animated React components for design engineers. Copy-paste ready components built with Framer Motion, Tailwind CSS, and Next.js — including accordion, slider, terminal, spotify card, QR code, pagination, magnetic dock, portal uploader, signature, number ticker, blur reveal, shimmer text, image trail, logo carousel, box carousel, command orbit, tactile highlight, rich button, and animated background components.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://klarden.vercel.app",
  github: "https://github.com/dev-o-los/klarden-ui",
  twitter: "@utkxrshdev_",
  author: "dev-o-los",
  authorUrl: "https://github.com/dev-o-los",
  defaultOgImage: "/og.png",
  keywords: [
    // Brand & product
    "Klarden UI",
    "Klarden components",
    // Primary category
    "React components",
    "React UI library",
    "animated React components",
    "Next.js components",
    "Next.js UI library",
    "copy paste React components",
    "shadcn alternative",
    "free React components",
    "open source UI library",
    "design engineering components",
    // Component-specific
    "accordion React component",
    "animated accordion",
    "React slider component",
    "media progress slider",
    "Mac terminal React component",
    "macOS terminal UI component",
    "Spotify card React component",
    "music player card React",
    "vinyl disc animation React",
    "portal uploader React",
    "drag and drop file upload React",
    "magnetic dock React",
    "macOS dock React component",
    "icon magnification effect React",
    "command orbit React",
    "radial command menu React",
    "label input React component",
    "floating label input React",
    "animated form input React",
    "QR code generator React",
    "QR code React component",
    "pagination React component",
    "animated pagination React",
    "logo carousel React",
    "infinite scroll logo carousel",
    "image trail React component",
    "cursor image trail effect",
    "box carousel React",
    "content carousel React",
    "blur reveal React component",
    "text reveal animation React",
    "shimmer text React",
    "text shimmer animation",
    "number ticker React",
    "counting animation React",
    "animated number counter",
    "tactile highlight React",
    "text highlight animation",
    "signature React component",
    "handwritten signature animation",
    "page not found React",
    "404 page React component",
    "orbit context menu React",
    "rich button React",
    "animated button React",
    // Background components
    "animated gradient background React",
    "WebGL gradient background",
    "ghost ether background React",
    "plasma wave background React",
    "animated starry sky React",
    "RNA lines background React",
    "WebGL shader background React",
    // Technology stack
    "Framer Motion components",
    "Tailwind CSS components",
    "TypeScript React components",
    "Next.js App Router components",
    "shadcn registry components",
    // Intent-based long-tail
    "react component with physics animation",
    "spring animation React components",
    "UI components for design engineers",
    "tactile UI components",
    "fluid motion React components",
    "premium React UI kit",
    "motion UI React library",
    "interactive React components",
    "microinteraction React components",
  ],
};

